config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tasks do
    get :completed, on: :member
    resources :comments, except: :index
  end
  resources :networks, only: %i[index show]
  get "statistics", to: "pages#statistics", as: "statistics"
  get "presentation", to: "pages#presentation", as: "presentation"

  resources :services, only: [] do
    resources :equipments, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  has_many_attached :photos
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :waterpoint_equipments
  has_many :waterpoints, through: :waterpoint_equipments
  has_many :tasks
  has_many :service_equipments
  has_many :services, through: :service_equipments
end

app/models/network.rb
class Network < ApplicationRecord
  has_many :waterpoints
  has_many :tasks
  has_many :services, through: :tasks

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def complete_tasks
    tasks.where(complete_task: true).count
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :service_equipments
  has_many :equipments, through: :service_equipments
end

app/models/service_equipment.rb
class ServiceEquipment < ApplicationRecord
  belongs_to :service
  belongs_to :equipment
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :manager, class_name: "User", foreign_key: "manager_id"
  belongs_to :technician, class_name: "User", foreign_key: "technician_id"
  belongs_to :equipment
  belongs_to :waterpoint
  belongs_to :network
  belongs_to :service
  has_many :comments
  has_many :users, through: :comments
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :tasks
  has_many :comments

  def tasks
    return Task.where(manager: self).or(Task.where(technician: self))
  end
end

app/models/waterpoint.rb
class Waterpoint < ApplicationRecord
  belongs_to :network
  has_many :tasks
  has_many :waterpoint_equipments
  has_many :equipments, through: :waterpoint_equipments

end

app/models/waterpoint_equipment.rb
class WaterpointEquipment < ApplicationRecord
  belongs_to :equipment
  belongs_to :waterpoint
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :technician, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :technician, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @task = Task.find(params[:task_id])
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    @comment.task_id = @task.id
    if @comment.save
      redirect_to task_path(@task), notice: 'Comment has been posted.'
    else
      render :new, :unprocessable_entity
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, photos: [])
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  def index
    @service = Service.find(params[:service_id])
    @equipments = @service.equipments

    respond_to do |format|
      format.html
      format.text { render partial: 'equipments/input', locals: { equipments: @equipments }, formats: [:html] }
    end
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  def index
    @networks = Network.all
    @markers = @networks.geocoded.map do |network|
      {
        lat: network.latitude,
        lng: network.longitude
      }
    end

    @waterpoints = Waterpoint.all
    @tasks = Task.all
  end

  def show
    @network = Network.find(params[:id])
    @markers = [{ lat: @network.latitude, lng: @network.longitude }]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @tasks = Task.all
    @networks = Network.all
    @tasks_completed = Task.where(end_date: Date.today).group(:complete_task).count
    @tasks_completed[:Complete] = @tasks_completed[true]
    @tasks_completed[:Incomplete] = @tasks_completed[false]
    @tasks_completed.except!(true)
    @tasks_completed.except!(false)
    @tasks_per_month = Task.where(complete_task: true).and(Task.where('end_date > ? AND end_date < ?', Date.new(Date.today.year, Date.today.month, 1), Date.new(Date.today.year, Date.today.month, 30))).group_by_day_of_month(:end_date).count
    p @tasks_per_month

  end

  def statistics
    @tasks_completed = Task.where(end_date: Date.today).group(:complete_task).count

    @tasks_completed[:Complete] = @tasks_completed[true]
    @tasks_completed[:Incomplete] = @tasks_completed[false]
    @tasks_completed.except!(true)
    @tasks_completed.except!(false)

    @technician_tasks = Task.joins(:technician).group("users.first_name").count


    @tasks_per_month = Task.where(complete_task: true).group_by_month(:end_date).count
    p @tasks_per_month
    # @tasks_Task.group_by_month(:end_date).count
    @tasks_per_month = @tasks_per_month.transform_keys { |key| key.strftime("%b %Y") }

    @split_tasks_per_month = Task.group(:complete_task).group_by_month(:end_date).count
    p @split_tasks_per_month
    @split_tasks_per_month = @split_tasks_per_month.transform_keys { |key| [key[0] == true ? "Complete" : "Incomplete", key[1].strftime("%b %Y")] }
  end

  def presentation
    render layout: "special_layout"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if current_user.technician == false
      @tasks = Task.all
    else
      @tasks = Task.where(technician: current_user)
    end
  end

  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
    @markers = [{ lat: @task.network.latitude, lng: @task.network.longitude }]
  end

  def new
    @task = Task.new
    @technician = User.where(technician: true).all
  end

  def create
    @task = Task.new(task_params)
    @task.network = Waterpoint.find(task_params[:waterpoint_id]).network
    @task.manager = current_user
    if @task.save!
      redirect_to root_path(@root)
    else
      render :new, :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to root_path, status: :see_other
  end

  def completed
    @task = Task.find(params[:id])
    @task.update_attribute(:complete_task, true)
    redirect_to root_path(@root)
  end

  private

  def task_params
    params.require(:task).permit(:start_date, :end_date, :extra_info, :service_id, :technician_id, :waterpoint_id, :equipment_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/equipments/_input.html.erb
<div class="mb-3 select required task_equipment">
  <label class="form-label select required" for="task_equipment">Equipment <abbr title="required">*</abbr></label>
  <select class="form-select select required" name="task[equipment_id]" id="task_equipment">
    <option value="" label=" "></option>
    <% equipments.each do |equipment| %>
      <option value="<%= equipment.id %>"><%= equipment.name %></option>
    <% end %>
  </select>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

  <%= favicon_link_tag %>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <title>MaintenanceTracker helping to save water all around Rwanda!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/layouts/special_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <title>MaintenanceTracker helping to save water all around Rwanda!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/networks/index.html.erb
<div class="d-flex">
  <%= render "shared/sidebar" %>
    <div class="networks-index flex-grow-1">
      <div class="all-networks">
        <div class="network-info-header">
          <li>NETWORK</li>
          <li>ADDRESS</li>
          <li>WATERPOINTS</li>
          <li>COMPLETE TASKS</li>
        </div>
        <% @networks.each do |network| %>
          <%= link_to network_path(network), class:"network-link" do %>
            <div class="single-network">
              <li> <%= network.name %> </li>
              <li> <%= network.address%></li>
              <li><%= network.waterpoints.map(&:waterpoint_type).join(", ") %></li>
              <li><%= network.complete_tasks %> /
              <%= network.tasks.count %></li>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/networks/show.html.erb
<div class="d-flex">

  <%= render "shared/sidebar" %>

  <div class="info-network flex-grow-1">

        <h1> NETWORK <%= @network.name.upcase %> </h1>
    <div class="network-show flex-grow-1">
      <div>

        <div class="network-top-info">
          <div class="maintenance-no">
            <div class="network-info-maintenance">
              <h5>No. of equipment installed:</h5>
              <p> 38</p>
            </div>
          </div>
          <div class="maintenance-no">
            <div class="network-info-maintenance">
              <h5>No. of total tasks:</h5>
              <p> <%= @network.tasks.count %></p>
            </div>
          </div>
          <div class="maintenance-no">
            <div class="network-info-maintenance">
              <h5>Status completed tasks:</h5>
              <p><%= @network.complete_tasks %>/<%= @network.tasks.count %></p>
            </div>
          </div>
        </div>

        <div class="flex-grow-1">
          <div class="header">
            <h4>NETWORK LOCATION: <%= @network.address %></h4>
          </div>
          <div style="width: 100%; height: 275px; border-radius: 10px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>

      </div>
      <div class="flex-grow-1">
        <div class="ps-4 h-100">
          <div class="installed-equipments h-100">
            <div class="board-info">
              <li>Installed equipment at network <%= @network.name.upcase %> </li>
            </div>
            <div class="equipment-info">
              <li>EQUIPMENT INSTALLED</li>
              <li>WATERPOINT</li>
              <li>WARRANTY</li>
              <li>NEXT MAINTENANCE</li>
            </div>
            <% @network.waterpoints.each do |waterpoint| %>
              <% waterpoint.equipments.each do |equipment| %>
                <div class="equipment-details">

                  <li><%= equipment.name %></li>
                  <li><%= waterpoint.waterpoint_type %></li>
                  <li class="<%= equipment.warranty_valid ? "valid" : "expired" %>"><%= equipment.warranty_valid ? "valid" : "expired" %></li>
                  <% if equipment&.tasks&.last&.service %>
                    <li><%= (equipment&.tasks&.last&.created_at + equipment&.tasks&.last&.service&.frequency.months).strftime("%d/%m/%Y") %></li>
                  <% else %>
                  <li>N/A</li>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <hr class="my-3">

    <div class="flex-grow-1;">
      <div class="equipments-networks">
        <div class="next-maintenance-task">
          <div class="board-info flex-grow-1">
            <li>NEXT MAINTENANCE TASK AT <%= @network.name.upcase %></li>
          </div>
          <div class="task-info">
            <li>TASK NAME</li>
            <li>WATERPOINT </li>
            <li>EQUIPMENT</li>
            <li>DATE</li>
            <li>TECHNICIAN</li>
            <li>MANAGER</li>
          </div>
          <% @network.tasks.order(end_date: :asc).each do |task| %>
            <div class="task-details">
            <li><%= task.service.name %></li>
            <li><%= task.waterpoint.waterpoint_type %></li>
            <li><%= task.equipment.name %></li>
            <li><%= (task.created_at + task.service.frequency.months).strftime("%d/%m/%Y") %></li>
            <li><%= task.technician.first_name.capitalize %> <%= task.technician.last_name.capitalize %></li>
            <li><%= task.manager.first_name.capitalize %> <%= task.manager.last_name.capitalize %></li>


            </div>
          <% end %>
        </div>
      </div>
    </div>
<hr>

  </div>
</div>

app/views/pages/home.html.erb
<div class="d-flex">
  <%= render "shared/sidebar" %>
  <div class="pages-content flex-grow-1">
    <div class="tasks-networks">
      <div class="tasks">
        <div class="board-info">
          <li><%= "RECENT TASKS" %></li>
          <li><%= link_to "See All Tasks", tasks_path(@tasks) %></li>
        </div>
        <div class="tasks-info">
          <li>TASK NAME</li>
          <li>TECHNICIAN</li>
          <li>CREATED</li>
          <li>NETWORK</li>
        </div>
        <% @tasks.last(5).reverse.each do |task| %>
          <div class="task-details">
            <li> <%= task.service.name %> </li>
            <li> <%= task.technician.first_name.capitalize %> <%= task.technician.last_name.capitalize %></li>
            <li> <%= time_ago_in_words(task.created_at) %> ago </li>
            <li> <%= task.network.name %> </li>
          </div>
        <% end %>
      </div>
      <div class="networks">
        <div class="network-info">
          <li><%= "NETWORKS" %></li>
          <li><%= link_to "See All Networks", networks_path(@networks) %></li>
        </div>
        <div class="network-chart">
          <div class="pie-chart-home">
            <%= pie_chart @tasks_completed, colors: ["#F69E36", "#0073de"], legend: true, width: "285px", height: "285px", donut: true  %>
          </div>
          </div>
        </div>
      </div>


      <div class="line">
        <div class="line-home">
          <li>STATISTICS FOR THIS MONTH</li>
          <li><%= link_to "See All Stats", statistics_path(@statistics) %></li>
        </div>
          <div class="line-chart">
        <%= column_chart @tasks_per_month, colors: ["rgba(246, 158, 54, 1)"], legend: false, height: "220px", discrete: true, label: "TOTAL OF TASKS"  %>
          </div>
        </div>
  </div>
</div>

app/views/pages/presentation.html.erb
<div class="d-flex">
  <div class="hero-banner" style="background-image: url(<%= asset_path 'background.jpg' %>)">
    <%= link_to root_path do %>
      <div class="home-link">
        <p class="mb-0">INUMA</p>
        <p class="mb-0">TRACK</p>
      </div>
    <% end %>
    <%= link_to root_path do %>
      <div class="home-link">
        <p>WATER ACCESS</p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="border: solid 1px rgba(228,201,160,.2);" >
  <div class="container-fluid">
    <div class="logo-link">
      <%= image_tag "logo.png" %>
      <%= link_to "MAINTENANCE TRACKER", tasks_path, style:"padding-left: -0.175rem; color: grey;" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-right: 50px;">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="name-and-role">
            <div class="name-div">
              <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
            </div>
            <div class="role-div">
              <% if current_user.technician %>
              <%= "TECHNICIAN" %>
              <% else %>
              <%= "MANAGER" %>
              <% end %>
            </div>
          </div>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, :width=>60, :height=>60, :gravity=>"faces", :crop=>"thumb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit my Profile", "#", class: "dropdown-item" %>
              <%= link_to "Presentation page", presentation_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">

  <div class="dashboard-menu">
    <div class="task-btn">
      <%= link_to "CREATE A TASK", new_task_path(@task), class:"btn btn-primary" %>
    </div>
    <ul class="ul-items">
      <li><%= link_to "HOME", root_path(@root) %></li>
      <li><%= link_to "STATS", statistics_path(@statistics) %></li>
      <li><%= link_to "TASKS", tasks_path(@tasks) %></li>
      <li><%= link_to "NETWORKS", networks_path(@networks) %></li>
    </ul>
  </div>

</div>

app/views/tasks/index.html.erb
<div class="d-flex" data-controller="tasks search-technician" >
  <% if current_user.technician == false %>
  <%= render "shared/sidebar" %>
  <% end %>
    <div class="tasks-index flex-grow-1">
      <div class="filter-bar justify-content-between">
        <div class="search-bar" style="height: 38px;">
          <%= form_with url: tasks_path, method: :get, html: {class:
            "mb-4", data: {search_technician_target: "form"}} do |f| %>
            <%= f.text_field :query,
                     class: "form-control",
                     placeholder: "Find a Technician",
                     value: params[:query],
                     data: {search_technician_target: "input",
                            action: "keyup->search-technician#update keyup->tasks#checkCompletedHidden"
                     } %>
          <% end %>
        </div>
        <div>
          <label for="complete">Hide Complete Tasks</label>
          <input type="checkbox" data-tasks-target='checkbox' data-action="click->tasks#hideComplete" name="complete">
        </div>

      </div>
        <div class="all-tasks" data-search-tasks-target="list" >
          <div class="task-info-header">
            <li>TASK NAME</li>
            <li>TECHNICIAN</li>
            <li>DUE DATE</li>
            <li>NETWORK</li>
            <li>STATUS</li>
          </div>
              <% @tasks.reverse.each do |task| %>
                <%= link_to task_path(task), class:"task-link" do %>
                <div class="single-task" data-search-technician-target="technician" data-name="<%= "#{task.technician.first_name} #{task.technician.last_name}" %>" data-tasks-target="hide" data-completed=<%= task.complete_task%> >
                  <li> <%= task.service.name %> </li>
                  <li> <%= task.technician.first_name.capitalize %> <%= task.technician.last_name.capitalize %></li>
                  <li> <%= task.end_date.strftime("%d/%m/%Y") %> </li>
                  <li> <%= task.network.name %> </li>
                  <li> <%= if task.complete_task
                  '<i class="fa-solid fa-circle"style="color: green;"></i> Complete'.html_safe
                  else
                  '<i class="fa-solid fa-circle" style="color: red;"></i> Incomplete'.html_safe
                  end %></li>
                </div>
                <% end %>
              <% end %>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="d-flex">
  <% if current_user.technician == false %>
  <%= render "shared/sidebar" %>
  <% end %>
    <div class="flex-container flex-grow-1">
      <div class="info flex-grow-1">
      <div class="top-info">
        <div>
          <h1> MAINTENANCE TASK ID <%= @task.id %> <% if current_user.technician == false %>
        <%= link_to edit_task_path(@task) do %>
            <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
        <% end %> </h1>
          <h2>Technician: <strong><%= @task.technician.first_name.upcase %> <%= @task.technician.last_name.upcase %></strong></h2>
          <h2>Assigned by: <strong><%= @task.manager.first_name.upcase %> <%= @task.manager.last_name.upcase %></strong></h2>
         <div class="status"> <%= if @task.complete_task
          '<i class="fa-solid fa-circle"style="color: green;"></i> Complete'.html_safe
          else
          '<i class="fa-solid fa-circle" style="color: red;"></i> Incomplete'.html_safe
          end %>
        </div>
        </div>

          <div class="date">
            <div class="start">
              <p>Start date:</p>
              <div class="time"><%= @task.start_date.strftime("%d.%m.%Y") %></div>
            </div>

            <div class="end">
              <p>End date:</p>
              <div class="time"><%= @task.end_date.strftime("%d.%m.%Y") %></div>
            </div>
          </div>

      </div>

        <div class="details">
          <p>DETAILS</p>
          <p> <%= @task.extra_info %></p>
        </div>

        <hr>

        <div class="details p-0">

          <div class="address">
            <div class="address-info p-3">
              <h3>SITE ADDRESS</h3>
              <ul>
                <div class="address-details">
                <li><strong>Network:</strong> <%= @task.network.name.upcase %></li>
                <li><strong>Waterpoint:</strong> <%= @task.waterpoint.waterpoint_type.upcase %></li>
                <li><strong>Address:</strong> <%= @task.network.address.upcase %></li>
                <li><strong>Manager:</strong> <%= @task.manager.first_name.upcase %> <%= @task.manager.last_name.upcase %></li>
                </div>
              </ul>
              <div class="equipment">
<hr>
            <h4>EQUIPMENT INFO</h4>
            <p>Equipment to be maintained: <strong><%= @task.equipment.name %></strong></p>
            </div>
            </div>
            <div class="flex-grow-1 d-flex justify-content-end">
              <div style="width: 80%; height: 100%; border-radius: 0 10px 10px 0"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          </div>
        </div>


        <div class="comments">
          <h4>COMMENTS</h4>
          <% @task.comments.each do |comment| %>
          <p><%= comment.content %></p>
          <p><%= time_ago_in_words(comment.created_at)%> ago</p>
            <% comment.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 250, width: 400, crop: :fill %>
            <% end %>
          <% end %>
        </div>
            <% if current_user.technician == true %>
              <div class="comment-new">
                <% if @task.comments.count < 1 %>
                  <%= simple_form_for [@task, @comment] do |f| %>
                  <%= f.input :content, label: 'Leave your comment' %>
                  <%= f.input :photos, label: 'Add your pictures', as: :file, input_html: { multiple: true } %>
                  <%= f.button :submit, 'POST', class: "btn btn-primary" %>
                  <% end %>
                <% end %>
              </div>
            <% end %>

            <% if @task.complete_task == false && @task.comments.count >= 1 %>
              <%= link_to "COMPLETE THE TASK", completed_task_path(@task), class: "btn btn-primary" %>
            <% end %>
            </div>
          </div>
        </div>
</div>